name: Deploy digest

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9,15,21,3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone bot repo
        uses: actions/checkout@v3
      - name: Clone digest repo
        uses: actions/checkout@v3
        with:
          path: .
          repository: melissawm/mastodon_digest
      - name: Copy style and custom index page
        run: |
          cp -R static mastodon_digest/render/.
          cp index.html.jinja mastodon_digest/templates/themes/light/.
          cp render-info.html.jinja mastodon_digest/templates/common/.

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create env file
        shell: bash
        env:
          MASTO_TOKEN: ${{ secrets.MASTODON_TOKEN }}
        run: |
          echo -e "MASTODON_TOKEN=$MASTO_TOKEN\nMASTODON_BASE_URL=https://bolha.us" > ../../.env
      - name: Build
        run: |
          python -m pip install -r requirements.txt
          python run.py --theme light
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: render

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
